### ISSUE TITLE
Error on validationEdit required fields

### ISSUE THREAD

**Issue by ingeniumdesign** [in2code-de/femanager#131]
please, dont Close the Issues https://github.com/in2code-de/femanager/issues/124! 

The 4.2.5 dont work in the Modus "Invitation password request"

@sbusemann => https://github.com/in2code-de/femanager/issues/124

**Comment by swisschocolate** [comment]
Got the same «Field could not be validated» general validation error message of required fields. The problem seems to be if the typoscript validation settings are on templates of subpages. As the Ajax request always goes to the base url, the validation settings of the form differ from the settings of the root page. 
I wanted to implement several registration forms on different pages for different user types with different validation settings. This doesn't work with client validation.

**Comment by buldozer86** [comment]
I got this error when extended flexform and added customer actions to 'Edit' controller. After fast debugging, I found the problem in [method](https://github.com/in2code-de/femanager/blob/develop/Classes/Domain/Repository/PluginRepository.php#L76). This condition not working for me because, in fact, we have hardcoded [there](https://github.com/in2code-de/femanager/blob/develop/Classes/Domain/Repository/PluginRepository.php#L20) and if you change something for 'switchableControllerActions' in flexform this condition will not work correctly. So my solution was extended repository **PluginRepository** and implement my owner logic for checking switchableControllerActions.

**Comment by stephangrass** [comment]
Same problem as swisschocolate.
It work's, if all field are set to required in the root page template and set the individual requirements in the templates of the subpage.

**Comment by sbusemann** [comment]
In the current version I can not reproduce it.
