### ISSUE TITLE
validation url fails if root page redirects to first subpage

### ISSUE THREAD

**Issue by MarkusLutum** [in2code-de/femanager#202]
I use t3bootstrap as a basis. In this Typo3 instance the root page automatically links to the first subpage.
So the root Home is of type ("Verweis" with "Erste Unterseite") This results into a 307 temp redirect.

So if the validation calls 
https://www.mypage.de/?type=1548935210
it returns with a 307 temp redirect and the browser calls 
https://www.mypage.de/first-subpage/ 
without the ?type parameter

Is this a bug or is there a workaround? I think this redirect root setup is quit common, or?

**Comment by svewap** [comment]
My suggestion would be to construct the URL for validation from the current page ID and the page type 1548935210, because other users with similar structures are certainly affected as well. I would render this as a JS constant in the form by fluid, so that the URL generation is also captured by the UrlBuilder and a "beautification" by route enhancer is possible.

**Comment by nollm** [comment]
+1

**Comment by toco3** [comment]
+1

**Comment by Patta** [comment]
+1
