### ISSUE TITLE
Dependence on CSS framework

### ISSUE THREAD

**Issue by webian** [in2code-de/femanager#274]
By default an extension should not be dependent on a specific CSS framework (in this case Twitter Bootstrap).

So the extension should not use CSS framework specific classes, in particular classes that alter the default aspect like `col-sm-2` or `col-sm-10`. Nowadays it's easy to extend a class with Less or Sass to make it display as the use case needs.

Instead it's hard to revert the display of a CSS framework class (ie: col-sm-x) to make it display as the use case needs.

**Comment by webian** [comment]
[More info about this concept](https://medium.com/@erik_flowers/how-youve-been-getting-the-bootstrap-grid-all-wrong-and-how-to-fix-it-6d97b920aa40)

**Comment by Moongazer** [comment]
In my opinion it is fine that an extension ships with a default setup for a certain framework, especially if its so common and widely used also by other TYPO3 extensions.

**BUT:** I do strongly recommend to replace all the template CSS class-names with TypoScript settings, so it would be easier to insert own class-names or add/change framework classes without modifying all the templates. The default TS setup can still based on Bootstrap.

Currently the problem is that the template files using "outdated" Bootstrap classes such as `form-horizontal` (since v4 using `form-group row` is the way to go). This problem for example affects all 26 partial-template files, so we've to copy/overwrite all of them (with all the trouble which comes if the original ones will be updated in the future). Instead, it would be much easier if all the classes coming from TypoScript settings like I mentioned above.

This would be a huge improvement for this great extension in my opinion.

**Comment by webian** [comment]
Please @Moongazer, read [this article](https://medium.com/@erik_flowers/how-youve-been-getting-the-bootstrap-grid-all-wrong-and-how-to-fix-it-6d97b920aa40) that I posted that explains what I mean better that I ever could. In particular the part "The Misconception".

In practice there is no need to change classes if they are semantic instead of something that define the aspect. The classes should label elements for what they are not for how they look. Establishing how they look is a task of the CSS.

**Comment by Moongazer** [comment]
@webian yes I did read the article and I understand the point (also I strongly agree to most of it). But on the other hand, this is just _one_ concept of how to do things, and I dislike if someone (or something in this case) is forcing me to work in a certain way, or in a certain concept. Let the user the freedom of choice.

Another point is, that there are many (hobby) developers out there which are not using SCSS for example, so they can't just define classes using mixins or whatever. Forcing the semantic-classes concept on them would mean, also forcing them to use SCSS (not everyone is a fullstack-dev).

And another point: have you heard about Tailwind? This is one of the fastest growing modern CSS frameworks from what I've read, it's becoming quite popular recently and it uses non-semantic classes. This shows me that the concept of semantic vs. non-semantic classes is just a matter of taste, which again leads to the statement: make it configurable and let the user choose what he prefers.

**Comment by webian** [comment]
Nothing and no one is forcing anyone here :)
I understand the "let the user freedom" but sometimes it costs in terms of added complexity so I think it's better to find a good balance.

Example for `<label>`...

Actual:
`<label for="femanager_field_firstName" class="col-sm-2 control-label">`
the problem here is that if a dev is using Twitter Bootstrap but want to change from 2 to 3 columns for sm devices, must overwrite a template or get crazy overriding the bootstrap grid rules for this single case.

Your propose:
`<label for="femanager_field_firstName" class="{$settings.css.formLabel}">`
it's ok, but this adds a complexity (typoscript config) that's not necessary.

Semantic way:
`<label for="femanager_field_firstName" class="control-label">`
this is the best approach IMHO.

You want to use a dynamic preprocessor like LESS? Then do something like:
`.control-label { &:extend(.col-sm-3); }`

You want to use pure CSS? Do:
`.control-label { ...your css code... }`

P.S.:
The fact that something is popular (Tailwind) doesn't necessarily mean that it's better. Or else: Wordpress > TYPO3; Toyota > Tesla; etc...
And it's a matter of taste until your project is not supposed to be used in different use cases by different users like a TYPO3 extension.

**Comment by Moongazer** [comment]
Like I said, I totally agree in general^^ My argumentation goes more into fitting both worlds together:

1) The semantic approach (pro devs):
**Pro:** cleaner solution; less CSS file weight; no (or less) chain-overwriting of classes, etc...
**Con:** is not ready out-of-the-box, the dev first needs to style e.g. `.femanager-label`; Or the extension ships with a custom pre-compiled style, which might just get partial overwritten/customized by devs, resulting in chain-overwriting again.

2) The config approach (hobby devs):
**Pro:** extension is styled and ready for usage out-of-the-box (especially if e.g. Bootstrap is widely used by other extensions as well), so its easy to implement; for pro-devs its easy to use semantic approach in the same time;
**Con:** The TS configuration (which I don't see as negative aspect, but well...)

So I'd suggest it like this:
`<label for="femanager_field_firstName" class="femanager-label {$settings.css.formLabel}">`
With TS default setting `settings.css.formLabel = col-sm-2 control-label` for Bootstrap.

1) For devs wanting the semantic approach:
- Set in TS `settings.css >`
- Define `.femanager-label` like you want

2) For hobby, lazy or prototyping devs:
- Nothing to do as its ready out-of-the-box (if they use Bootstrap, like many T3 extension does)
- Otherwise: replacing their own CSS framework classes in TS

**Comment by sbusemann** [comment]
The templates can be overwritten and mostly twitter bs is wanted. Also I will not introduce a breaking change atm.
