### ISSUE TITLE
LogicException "ControllerName is not allowed" using registration form in modal

### ISSUE THREAD

**Issue by geodem** [in2code-de/femanager#303]
Hello,

I created a template partial which loads the login/registration page in a div with display:none. This div is being displayed as a modal by clicking a specific link. Everything works fine, even validation. However on clicking "Create Profile Now" I get the error LogicException "ControllerName is not allowed". How can I fix this?

Thanks!
Georg

**Comment by janhelke** [comment]
This is due to \In2code\Femanager\Domain\Validator\AbstractValidator::checkAllowedControllerName 
Basically it checks, if there is a femanger plugin in tt_content table stored for the page you are currently on. I dislike this approach and see no use for this check.
Nevertheless a feasible workaround might be to create a "RegistrationPage" with the registration plugin and add this to your form declaration: 
```
<f:form
    [...]
    pageUid="<registrationPageUid>"
    [...]
>
```

**Comment by sbusemann** [comment]
@janhelke thanks for the tipp - I will close this issue
