### ISSUE TITLE
"confirmation" tabs in the femanger module causing errors

### ISSUE THREAD

**Issue by hakuh** [in2code-de/femanager#465]
After updating a TYPO3 10 version to 11 i got the following errors when i'm using the confirmation tabs in the FE Manager module:

"Admin Confirmation" -> click on the confirm hook causes the error "Class 'In2code\Femanager\Controller\RequestFactory' not found" in line 3221 of GeneralUtility.php

"Open User Confirmations" -> click on "resend user confirmation email" icon causes the error "Call to a member function sL() on null" in line 4396 of ContentObjectRenderer.php

**Comment by peterschoene** [comment]
Line 238 of [UserBackendController.php](https://github.com/in2code-de/femanager/blob/19191f5cee4084683fd9bcdb10e861242f5cab8a/Classes/Controller/UserBackendController.php#L248C1-L248C152) uses RequestFactory. But it is not defined.
Manually adding the 
use TYPO3\CMS\Core\Http\RequestFactory; doesn't resolve the problem for me, but makes it even worse:

`(1/1) GuzzleHttp\Exception\ConnectException
cURL error 6: Could not resolve host: ***** (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://*****/?tx_femanager_pi1%5Baction%5D=confirmCreateRequest&tx_femanager_pi1%5Bcontroller%5D=New&tx_femanager_pi1%5Bhash%5D=6c8c76fae1234444&tx_femanager_pi1%5Bstatus%5D=adminConfirmation&tx_femanager_pi1%5Buser%5D=399&cHash=dec168e82b09fa49aa4d9a37f5aa1c44`

**Comment by denvis** [comment]
I was able to write a patch for TYPO3 v11. In addition to the use statement, an error occurs in the NewController.php because the response in an ActionController now has to come via the ResponseFactory

`-            $this->eventDispatcher->dispatch(new AfterRequestDispatchedEvent($this->request, $this->response));
+            $this->eventDispatcher->dispatch(new AfterRequestDispatchedEvent($this->request, $this->responseFactory->createResponse()));`

**Comment by sbusemann** [comment]
In Version 8 (TYPO3 12) the confirmation functions works generally. At the moment I need to adjust the Backend Controller due to a not working security issue. So I will close this issue, as this functions works in the main verison.
