### ISSUE TITLE
Crushed Session data on registration

### ISSUE THREAD

**Issue by Skiud** [in2code-de/femanager#57]
If I'm right, there is a conflict between typo3 sessionData storage methods and registration autologin option in femanager.

It seems like login() function of UserUtility crushes existing sessionData seted and geted with the standard methods below
$GLOBALS["TSFE"]->fe_user->setKey('ses', 'theValueIWantBeforeAndAfterRegistration', $value);
$GLOBALS["TSFE"]->fe_user->getKey('ses', 'theValueIWantBeforeAndAfterRegistration');

But when Login() is called, the fetchUserSession() [L314 in UserUtility] method erases existing data.

The goal is to use femanager extension to create an account and do autologin just before payment page (shop&basket system for example).

**Comment by einpraegsam** [comment]
Did you test the settings in extension manager? There is (don't know the exact spelling at the moment) an experimental checkbox for people with login problems.

**Comment by Skiud** [comment]
Yes I tried the extension manager Alternative Login option but it is not exactly the same issue. 
In fact the login() function is effective, it just doesn't keep already set session data.

If you stored in 'ses' sessionData some values for example products in basket, after registration + autologin they are lost.

A solution to fix it may be
1. Set a typoscript configuration value in setup.txt to configurate a sessionKey (the key of the own developper dataSession)
2. In login() function of UserUtility, get the sessionData from the configured key
3. Execute createUserSession(), fetchUserSession()
4. And finaly put back sessionData just after  $tsfe->fe_user->setAndSaveSessionData('ses', true);

**Comment by einpraegsam** [comment]
Femanager does not handle FE-User Login or Session handling it just helps with an autologin after a registration. Please adjust your TYPO3 in the right way.
BTW: Using 'ses' will lose session if browser gets closed from the visitor. You have to use 'user' together with a frontend login - but that's not part of femanager.

**Comment by Skiud** [comment]
Ok, thanks for your time

**Comment by nollm** [comment]
I have the same problem like @Skiud.

On my website is a shop where users can add products to the basket without logged in.
After registration and autologin the basket is empty.

The problem seems to be in UserUtility->login().

![userutility_login](https://user-images.githubusercontent.com/42864489/78125335-2c04ce80-7411-11ea-8331-1c4c8deb1300.png)

The following line overrides the ses_data where the basket content is stored.
`$tsfe->fe_user->user = $tsfe->fe_user->fetchUserSession();`

Here you see the state before autologin.
![session_before_login](https://user-images.githubusercontent.com/42864489/78125478-5f475d80-7411-11ea-9091-8a8c7ec14e61.png)

And here the state after autologin.
![session_after_login](https://user-images.githubusercontent.com/42864489/78125505-679f9880-7411-11ea-8ac5-4e0a77158e2f.png)

Do you have a solution how to fix it?
