### ISSUE TITLE
Where to setup module.tx_femanager.settings.configPID? 

### ISSUE THREAD

**Issue by spiderrider** [in2code-de/femanager#84]
Typo3 8.7.13
femanager 4.2.2

Since version 4.2 I get in the backend under WEB > Frontend Users the following error message:
No TypoScript found. Did you already setup module.tx_femanager.settings.configPID in your PageTS?

In the manual I don't find anything about module.tx_femanager.settings.configPID.
In the manual I found this note: All settings for the backend module are done in ext_typoscript_setup.txt in the key module.tx_femanager.
But I also found neither ext_typoscript_setup.txt nor module.tx_femanager.

Does anybody had the same problems and knows a solution?

BTW Since this error message it's not possible to register.

Thank you

**Comment by sbusemann** [comment]
it can be found in femanager/Documentation/Installation/Index.rst

In order to supply all functions also in BE, a page is needed, where the whole frontend ts configuration can be loaded from. 

So please set module.tx_femanager.settings.configPID = 1 at your root page of your installation (and replace 1 with the page where the femanger ts can be found)

**Comment by sbusemann** [comment]
@spiderrider can you please check my comment

**Comment by spiderrider** [comment]
Thank you very much, your explanation helped, I understood how to setup module.tx_femanager.settings.configPID and now femanager works perfect.
